
// Objective-C API for talking to the following Go packages
//
//	filippo.io/age
//	github.com/MarinX/agemobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Age_FRAMEWORK_H__
#define __Age_FRAMEWORK_H__

#include "Age.objc.h"
#include "Agemobile.objc.h"
#include "Universe.objc.h"

#endif
