// Objective-C API for talking to github.com/MarinX/agemobile Go package.
//   gobind -lang=objc github.com/MarinX/agemobile
//
// File is generated by gobind. Do not edit.

#ifndef __Agemobile_H__
#define __Agemobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Age.objc.h"

/**
 * Decrypt decrypts an input for provided keys seperated with new lines
 */
FOUNDATION_EXPORT NSString* _Nonnull AgemobileDecrypt(NSString* _Nullable keys, NSString* _Nullable input, NSError* _Nullable* _Nullable error);

/**
 * Decrypt decrypts an input file path to output file path for provided keys seperated with new lines
 */
FOUNDATION_EXPORT BOOL AgemobileDecryptFile(NSString* _Nullable keys, NSString* _Nullable input, NSString* _Nullable output, NSError* _Nullable* _Nullable error);

/**
 * Encrypt encryptes an input for provided recipients seperated with new lines
 */
FOUNDATION_EXPORT NSString* _Nonnull AgemobileEncrypt(NSString* _Nullable recipients, NSString* _Nullable input, BOOL withArmor, NSError* _Nullable* _Nullable error);

/**
 * EncryptFile encryptes an input file path to output file path for provided recipients seperated with new lines
 */
FOUNDATION_EXPORT BOOL AgemobileEncryptFile(NSString* _Nullable recipients, NSString* _Nullable input, NSString* _Nullable output, BOOL withArmor, NSError* _Nullable* _Nullable error);

/**
 * GenerateX25519Identity randomly generates a new X25519Identity.
 */
FOUNDATION_EXPORT AgeX25519Identity* _Nullable AgemobileGenerateX25519Identity(NSError* _Nullable* _Nullable error);

/**
 * ParseX25519Identity returns a new X25519Identity from a Bech32 private key
encoding with the "AGE-SECRET-KEY-1" prefix.
 */
FOUNDATION_EXPORT AgeX25519Identity* _Nullable AgemobileParseX25519Identity(NSString* _Nullable s, NSError* _Nullable* _Nullable error);

/**
 * ParseX25519Recipient returns a new X25519Recipient from a Bech32 public key
encoding with the "age1" prefix.
 */
FOUNDATION_EXPORT AgeX25519Recipient* _Nullable AgemobileParseX25519Recipient(NSString* _Nullable s, NSError* _Nullable* _Nullable error);

#endif
