name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.17
        check-latest: true
    - name: Ensure gomobile is installed.
      run: go install golang.org/x/mobile/cmd/gomobile@latest && gomobile init
    - name: Build
      run: make build-ios
