name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - uses: actions/setup-go@v4
      with:
        go-version: '1.17'
        check-latest: true
    - name: Test
      run: make
